#!/bin/sh

# Log this!
exec &> >(tee -a "/tmp/bspwm.log")

#
# MONITOR CONFIGURATION
#
n_monitors=$(xrandr -q | grep -w connected | wc -l)
if [ $n_monitors -eq 2 ]; then
	LEFT=HDMI-A-2
	RIGHT=HDMI-A-3

	xrandr --output $RIGHT --primary
	xrandr --output $LEFT --left-of $RIGHT
fi

#
# AUTOSTART
#
sxhkd &
setxkbmap es &
xsetroot -cursor_name left_ptr &
picom --config ~/.config/picom.conf &
nitrogen --restore &
polybar main &
if [ $n_monitors -eq 2 ]; then
	# Wait before launching the second bar so that
	# the system tray appears in the main one.
	bash -c "sleep 2; polybar second" &
fi
fcitx &
numlockx &
protonmail-bridge --no-window &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
telegram-desktop -startintray &
wmname compiz & # Fix Java applications
/usr/lib/notification-daemon-1.0/notification-daemon &	# (Gnome) notification daemon
megasync &
kdeconnect-indicator &

which syncthing &> /dev/null
if [ $? -eq 0 ]; then
	syncthing -no-browser &
fi

xset -dpms s off	# Do not turn off the screen!

#
# TOUCHPAD THINGS
#
if [ -f "$(which synclient)" ]; then
	synclient TapButton1=1
	synclient TapButton2=3
	synclient TapButton3=2
fi

#
# MOUSE SENSITIVITY
#
#if [ $n_monitors -eq 2 ]; then
#	xinput set-prop 10 "Coordinate Transformation Matrix" 0.4 0 0 0 0.4 0 0 0 1
#fi

#
# MONITOR(S)
#

if [ $n_monitors -eq 1 ]; then
	# Laptop
	bspc monitor -d I II III IV V VI VII VIII IX X
else
	# Desktop
	# If at some point fails, run xrandr here.
	bspc monitor $LEFT -d I III V VII IX
	bspc monitor $RIGHT -d II IV VI VIII X
fi

#
# CONFIG
#
bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# This is meant to help with the electron-based apps bug, but I think it doesn't :(
#bspc config ignore_ewmh_focus true
# Grab the mouse events at 144Hz, which makes window movement/resizing much smoother.
bspc config pointer_motion_interval 7
# I don't like tiling. Why am I using bspwm then? I'll create my own WM at some point.
bspc rule -a "*:*:*" state=floating
# All desktops are in monocle layout
for i in I II III IV V VI VII VIII IX X; do
	bspc desktop $i -l monocle
done

#
# CUSTOM PROGRAMS CONFIG
#
# This should also help the discord bug. I'm not sure if it does either :(
bspc rule -a discord follow=off

export BROWSER="$(which firefox)"
xdg-mime default firefox.desktop x-scheme-handler/https
xdg-mime default firefox.desktop x-scheme-handler/http
