#! /bin/sh

#
# AUTOSTART
#
sxhkd &
setxkbmap es &
xsetroot -cursor_name left_ptr &
compton &
nitrogen --restore &
polybar main &
fcitx &
numlockx &
protonmail-bridge --no-window &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#
# TOUCHPAD THINGS
#
if [ -f "$(which synclient)" ]; then
	synclient TapButton1=1
	synclient TapButton2=3
	synclient TapButton3=2
fi

#
# MONITOR
#
bspc monitor -d I II III IV V VI VII VIII IX X

#
# CONFIG
#
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#
# CUSTOM PROGRAMS CONFIG
#
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a Alacritty state=floating
