#import = [
#    "~/.config/alacritty/themes/themes/chicago95.toml"
#]

[env]
TERM = "xterm-256color"

[window.padding]
x = 0
y = 0

[font]
size = 13

[font.normal]
family = "BigBlueTermPlus Nerd Font"

[cursor]
style = "Block"
unfocused_hollow = true

[terminal.shell]
program = "zsh"
args = ["-c", "tmux"]
