(deftheme VIVALAVIDA
  "Created 2024-04-04.")

(custom-theme-set-faces
 'VIVALAVIDA
 '(cursor ((t (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#36D8BD"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#D85F00"))))
 '(highlight ((t (:foreground "#0F1019" :background "#D85F00"))))
 '(region ((t (:extend t :background "#1E1E33"))))
 '(shadow ((t (:foreground "#767676"))))
 '(secondary-selection ((t (:extend t :background "#767676"))))
 '(trailing-whitespace ((t (:background "#D83441"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#3679D8"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "gray" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "white" :weight bold))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit font-lock-function-name-face))))
 '(font-lock-function-name-face ((t (:foreground "yellow"))))
 '(font-lock-keyword-face ((t (:foreground "#FF0000"))))
 '(font-lock-negation-char-face ((t (:foreground "#3679D8" :inherit (bold)))))
 '(font-lock-number-face ((t (:foreground "#D85F00"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#3679D8" :inherit (bold)))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#3679D8" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#3679D8" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "green"))))
 '(font-lock-type-face ((t (:foreground "deep sky blue"))))
 '(font-lock-variable-name-face ((t (:foreground "magenta"))))
 '(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit link))))
 '(link ((t (:foreground "#00FF00" :underline t :weight bold))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#585C6C" :inherit (default)))))
 '(header-line ((t (:inherit mode-line))))
 '(tooltip ((t (:foreground "#CEDBE5" :background "#040408"))))
 '(mode-line ((t (:background "gray" :box nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#D85F00"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#B2B2B2" :background "#030306"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#0F1019" :background "#D83441"))))
 '(lazy-highlight ((t (:weight bold :foreground "#D0D0D0" :background "#974200"))))
 '(match ((t (:weight bold :foreground "#79D836" :background "#0F1019"))))
 '(next-error ((t (:inherit (region)))))
 '(centaur-tabs-default ((t (:background "black"))))
 '(centaur-tabs-selected ((t (:background "gray" :foreground "black"))))
 '(centaur-tabs-selected-modified ((t (:background "gray" :foreground "black"))))
 '(centaur-tabs-unselected-modified ((t (:background "black" :foreground "white"))))
 '(centaur-tabs-unselected ((t (:background "black" :foreground "white"))))
 '(treemacs-git-modified-face ((t (:foreground "magenta"))))
 '(treemacs-git-added-face ((t (:foreground "green"))))
 '(treemacs-hl-line-face ((t (:background "gray" :foreground "black"))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 151 :width normal :foundry "SRC" :family "Hack Nerd Font"))))
 '(treemacs-directory-face ((t (:foreground "white")))))

(provide-theme 'VIVALAVIDA)
