#!/bin/sh -eu

INCLUDE="install"

dotfiles_execute() {
	install_execute git || assert_last_ok

	if [ ! -d "$HOME/git/dotfiles" ]; then
		git clone https://github.com/jlxip/dotfiles "$HOME/git/dotfiles" 2>&1
	else
		cd "$HOME/git/dotfiles"
		git pull 2>&1
		cd -
	fi
}

EXECUTE="dotfiles_execute"
