#!/bin/sh -e

INCLUDE="os distro sudo"

function updateCerts_execute() {
	sudo_execute systemctl stop nginx
	sudo_execute certbot renew
	sudo_execute systemctl start nginx
}

EXECUTE="updateCerts_execute"
